sudo: required

language: bash

services:
  - docker

env:
  - VERSION=1.632
  - VERSION=1.626
  - VERSION=1.620
  - VERSION=1.617
  - VERSION=1.616
  - VERSION=1.615
  - VERSION=1.614
  - VERSION=1.613
  - VERSION=1.612
  - VERSION=1.609

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

before_script:
  - env | sort
  - cd "$VERSION"
  - DOCKER_IMAGE="jenkins"

script:
  - docker build -t ${DOCKER_IMAGE}:${VERSION} .
  - bats tests
